// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateForum(arg1) {
  return window['go']['main']['App']['CreateForum'](arg1);
}

export function GetForums() {
  return window['go']['main']['App']['GetForums']();
}

export function SingularScrape(arg1) {
  return window['go']['main']['App']['SingularScrape'](arg1);
}
