// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateForum(arg1:models.Forum):Promise<string>;

export function DeleteForum(arg1:string):Promise<void>;

export function Extract_posts(arg1:string):Promise<number>;

export function GetChartData(arg1:string):Promise<Array<models.Chart>>;

export function GetForums():Promise<Array<models.Forum>>;

export function GetPosts(arg1:string):Promise<Array<models.Post>>;

export function MultipleScrape(arg1:Array<models.Forum>):Promise<Array<models.Forum>>;

export function ScanPosts(arg1:string):Promise<void>;

export function SingularScrape(arg1:models.Forum):Promise<void>;
