// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateForum(arg1:models.Forum):Promise<string>;

export function GetForums():Promise<Array<models.Forum>>;

export function SingularScrape(arg1:models.Forum):Promise<string>;
